[package]
name = "oxidite-cli"
version = "0.1.0"
edition = "2021"
authors = ["Meshack Bahati Ouma <bahatikylemeshack@gmail.com>"]

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
bytes = "1.10.0"
http-body-util = "0.1.2"
hyper = "1.6.0"
oxidite-core = { path = "../oxidite-core" }
oxidite-middleware = { path = "../oxidite-middleware" }
oxidite-db = { path = "../oxidite-db" }
oxidite-config = { path = "../oxidite-config" }
tokio = { version = "1.42.0", features = ["full"] }
chrono = "0.4.42"
dialoguer = "0.11.0"
colored = "2.2.0"
notify = "6.1.1"
